#5 create db using prisma, additional test migration
jchabrowski/coach-panel-app pull request #6
Opened 2024-01-25 21:11 UTC by jchabrowski

2024-01-27 19:25 UTC, lrozanski requested changes

2024-01-27 19:25 UTC, lrozanski commented on backend/prisma/migrations/20240106184053_init/migration.sql
> +    CONSTRAINT "trainer_pkey" PRIMARY KEY ("trainer_id")
Add an `fk_personal_info_id` foreign key

2024-01-27 19:25 UTC, lrozanski commented on backend/prisma/migrations/20240106184053_init/migration.sql
> +    CONSTRAINT "trainee_pkey" PRIMARY KEY ("trainee_id")
Add an `fk_trainer_id` and `fk_personal_info_id` foreign keys

2024-01-27 19:25 UTC, lrozanski commented on backend/prisma/migrations/20240106184053_init/migration.sql
> +    "trainer_id" BIGINT NOT NULL,
This should only be `NOT NULL` if it's impossible to create a trainee without an assigned trainer. This seems wrong, as presumably a trainee can switch trainers at some point.

2024-01-27 19:25 UTC, lrozanski commented on backend/prisma/migrations/20240106184053_init/migration.sql
> +    CONSTRAINT "personal_info_pkey" PRIMARY KEY ("personal_info_id")
Add a `uk_email` unique key constraint. We probably don't want multiple users to share an email. Also, think about login even though you're not working on it right now. The `personal_info` table having a `password` field seems weird. Not an issue for now, but something to think about

2024-01-27 19:25 UTC, lrozanski commented on backend/prisma/migrations/20240106184053_init/migration.sql
> +    CONSTRAINT "weight_info_pkey" PRIMARY KEY ("id")
Add an `fk_personal_info_id` foreign key constraint

2024-01-27 19:25 UTC, lrozanski commented on backend/prisma/migrations/20240106184053_init/migration.sql
> +    CONSTRAINT "training_block_pkey" PRIMARY KEY ("training_block_id")
Add the `fk_trainer_id` and `fk_trainee_id` foreign keys

2024-01-27 19:25 UTC, lrozanski commented on backend/prisma/migrations/20240106184053_init/migration.sql
> +    CONSTRAINT "training_session_pkey" PRIMARY KEY ("training_session_id")
Add an `fk_training_block_id` foreign key

2024-01-27 19:25 UTC, lrozanski commented on backend/prisma/migrations/20240106184053_init/migration.sql
> +    "training_session_id" INTEGER NOT NULL,
We should probably use `BIGINT` for this as well. Also, add an `fk_training_session_id` foreign key

2024-01-27 19:25 UTC, lrozanski commented on backend/prisma/migrations/20240106184053_init/migration.sql
> +    CONSTRAINT "exercise_pkey" PRIMARY KEY ("exercise_id")
Add an `fk_session_part_id` foreign key

2024-01-27 19:25 UTC, lrozanski commented on backend/prisma/migrations/20240106184053_init/migration.sql
> +    "indexed_key" VARCHAR(255) NOT NULL,
Just `key` is fine, or `name` if `key` is not allowed

2024-01-27 19:25 UTC, lrozanski commented on backend/prisma/migrations/20240106184053_init/migration.sql
> +    "value" VARCHAR(255),
This field can pretty much contain anything. Will 255 be enough?

2024-01-27 19:25 UTC, lrozanski commented on backend/prisma/migrations/20240106184053_init/migration.sql
> +    CONSTRAINT "exercise_metadata_pkey" PRIMARY KEY ("id")
Add an `fk_excercise_id` foreign key

2024-01-27 19:25 UTC, lrozanski commented on backend/prisma/migrations/20240106184053_init/migration.sql
> +CREATE UNIQUE INDEX "exercise_metadata_indexed_key_key" ON "exercise_metadata"("indexed_key");
Remember to update index names if you change any columns

2024-01-27 19:25 UTC, lrozanski commented on backend/prisma/migrations/20240124200825_24_01_24_add_exercise_data_test/migration.sql
> +ALTER TABLE "exercise" ADD COLUMN     "repetitions" INTEGER,
We should keep the schema in the `backend/prisma/migrations/20240106184053_init/migration.sql`, since this has never been deployed and we don't actually have to worry about migration order.

2024-01-27 19:25 UTC, lrozanski commented on backend/prisma/schema.prisma
> +// This is your Prisma schema file,
Regenerate your schema from the updated migration, or apply the changes here and regenerate the migration file. Whichever way is easier

2024-01-27 19:25 UTC, lrozanski commented on backend/prisma/schema.prisma
> +
Keep at most one empty line at the end of any file

2024-01-30 20:19 UTC, jchabrowski commented on backend/prisma/migrations/20240106184053_init/migration.sql
> +    "value" VARCHAR(255),
Let's see how this one plays out later on?

2024-01-31 10:28 UTC, jchabrowski commented on backend/prisma/migrations/20240106184053_init/migration.sql
> +    CONSTRAINT "personal_info_pkey" PRIMARY KEY ("personal_info_id")
IMO both login and email should work as login credentials.

2024-01-31 12:47 UTC, jchabrowski commented on backend/prisma/schema.prisma
> +  trainee          trainee          @relation(fields: [id], references: [trainer_id])
fields: [trainer_id]

2024-01-31 13:14 UTC, lrozanski commented on backend/prisma/schema.prisma
> +  trainee          trainee          @relation(fields: [id], references: [trainer_id])
`trainees trainee[]`, because it's a one to many relationship

2024-02-01 11:49 UTC, lrozanski commented on backend/prisma/schema.prisma
> +  id               BigInt           @id @unique @default(autoincrement())
@id creates primary key, which is already unique. Remove @unique

2024-02-01 11:55 UTC, lrozanski commented on backend/prisma/schema.prisma
> +  trainer_id       BigInt           @unique
Setting `@unique` on the `trainee` table means that there can't exist two rows with the same `trainer_id`. Effectively meaning one trainer can only train one trainee at a time.

2024-02-01 11:58 UTC, lrozanski commented on backend/prisma/schema.prisma
> +  training_block_id BigInt         @unique
Do we want to allow more than one training session per block? If so, remove `@unique`

2024-02-01 12:01 UTC, lrozanski commented on backend/prisma/schema.prisma
> +  date              DateTime       @unique
Only one session on a given day for the entire table?

2024-02-01 12:05 UTC, lrozanski commented
In addition to the comments above make sure to resolve any conflicts

2024-02-01 13:57 UTC, jchabrowski commented on backend/prisma/schema.prisma
> +  date              DateTime       @unique
deleting @unique for now

2024-02-01 16:09 UTC, lrozanski commented on backend/prisma/schema.prisma
> +  personal_info_id BigInt
Missing `@relation`

2024-02-01 17:00 UTC, lrozanski approved these changes

2024-02-01 17:02 UTC, merged